// <auto-generated />
using System;
using CRUDSmith.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace projetos.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20230303233521_initialDefensiveTable")]
    partial class initialDefensiveTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRUDSmith.Models.Defensive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DefensiveBonus")
                        .HasColumnType("integer")
                        .HasColumnName("base_damage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredStrength")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_damage");

                    b.Property<string>("SlotToUse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slot_to_use");

                    b.Property<string>("SpecialBonusGiven")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("special_bonus_given");

                    b.HasKey("Id");

                    b.ToTable("defensives", (string)null);
                });

            modelBuilder.Entity("CRUDSmith.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseDamage")
                        .HasColumnType("integer")
                        .HasColumnName("base_damage");

                    b.Property<int>("BonusDamage")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_damage");

                    b.Property<string>("BonusDamegeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bonus_damage_type");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlotToUse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slot_to_use");

                    b.Property<string>("SpecialBonusGiven")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("special_bonus_given");

                    b.HasKey("Id");

                    b.ToTable("weapons", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
